apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-monitoring-app
  labels:
    app: node-monitoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-monitoring-app
  template:
    metadata:
      labels:
        app: node-monitoring-app
    spec:
      containers:
        - name: node-monitoring-app
          image: 615300991839.dkr.ecr.us-east-1.amazonaws.com/node-devsecops-repository:1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20