apiVersion: v1
kind: Service
metadata:
  name: node-monitoring-app
spec:
  selector:
    app: node-monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer